me: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # this workflow contains a single job called "build"
  build:
   runs-on: ubuntu-latest

   #steps represent a sequence of taks that will be executed as part of the job 
   steps:
    - name: "Display message"
      run: echo "library"
   
